services:
  nginx:
    image: nginx:latest
    container_name: sdf_nginx_container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ./src/staticfiles:/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pos_api_server 
    networks:
      - app-network

  pos_api_server:
    build: .
    container_name: pos_api_server_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge