# Generated by Django 5.0.4 on 2025-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bundle_barcode_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundle',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
