# Generated by Django 5.0.4 on 2025-04-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0003_transactionlineitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionLineItem',
            new_name='TransactionItem',
        ),
    ]
