# Generated by Django 5.0.4 on 2025-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_rename_transactionlineitem_transactionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionproduct",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transactionproduct",
            name="promotion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transactionproduct",
            name="custom_discount_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionproduct",
            name="custom_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
