# Generated by Django 5.0.4 on 2025-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_transactionproduct_final_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionproduct",
            old_name="custom_discount_rate",
            new_name="discount_rate",
        ),
        migrations.RenameField(
            model_name="transactionproduct",
            old_name="custom_price",
            new_name="price",
        ),
        migrations.AddField(
            model_name="transactionproduct",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
