# Generated by Django 5.0.4 on 2025-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0006_rename_custom_discount_rate_transactionproduct_discount_rate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionproduct",
            name="default",
            field=models.BooleanField(default=True),
        ),
    ]
