# Generated by Django 5.0.4 on 2025-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_transactionproduct_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
