# Generated by Django 5.0.4 on 2025-05-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_transaction_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="transactionitem",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="TransactionBundle",
        ),
        migrations.DeleteModel(
            name="TransactionItem",
        ),
    ]
