# Generated by Django 5.0.4 on 2025-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_remove_transactionitem_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="changed_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="received_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
