# Generated by Django 5.0.4 on 2025-05-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_transaction_changed_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="changed_amount",
            new_name="change",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="received_amount",
        ),
    ]
