# Generated by Django 5.0.4 on 2025-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_rename_changed_amount_transaction_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
