# Generated by Django 5.0.4 on 2025-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_transaction_transaction_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="total_price",
            new_name="final_gst",
        ),
        migrations.AddField(
            model_name="transaction",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transactionproduct",
            name="final_gst",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transactionproduct",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
