# Generated by Django 5.0.4 on 2025-05-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_rename_total_price_transaction_final_gst_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactioncurrency",
            old_name="amount",
            new_name="payment",
        ),
    ]
