# Generated by Django 5.0.4 on 2025-05-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_rename_amount_transactioncurrency_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionproduct",
            name="default",
        ),
    ]
