# Generated by Django 5.0.4 on 2025-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
