# Generated by Django 5.0.4 on 2025-05-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_defaultgroup_inboundgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="InboundGroup",
        ),
        migrations.CreateModel(
            name="IntInboundGroup",
            fields=[],
            options={
                "verbose_name": "Group (INT Inbound)",
                "verbose_name_plural": "Groups (INT Inbound)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("groups.group",),
        ),
        migrations.CreateModel(
            name="KrInboundGroup",
            fields=[],
            options={
                "verbose_name": "Group (KR Inbound)",
                "verbose_name_plural": "Groups (KR Inbound)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("groups.group",),
        ),
        migrations.AddField(
            model_name="group",
            name="people",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.place",
            ),
        ),
    ]
